=== AdachiHjm/zerodrive/src/main/resources/zerodrive/util/logging/logging_1_0.dtd
<!ENTITY % Boolean "(true|false)">
<!ENTITY % ClassName "CDATA">
<!ENTITY % Integer "CDATA">

<!ELEMENT logging (handler+, logger+, root?)>
<!ATTLIST logging
    name CDATA #REQUIRED
>

<!ELEMENT handler (property*, filter*, formatter?)>
<!ATTLIST handler
    name     ID          #REQUIRED
    class    %ClassName; #REQUIRED
    encoding CDATA       #IMPLIED
    level    CDATA       #IMPLIED
    builder  %ClassName; #IMPLIED
>

<!ELEMENT filter (property*)>
<!ATTLIST filter
    class   %ClassName; #REQUIRED
    builder %ClassName; #IMPLIED
>

<!ELEMENT formatter (property*)>
<!ATTLIST formatter
    class   %ClassName; #REQUIRED
    builder %ClassName; #IMPLIED
>

<!ELEMENT logger (handler-ref+)>
<!ATTLIST logger
    name       CDATA #REQUIRED
    additivity %Boolean; #REQUIRED
    level      CDATA #IMPLIED
    resource   CDATA #IMPLIED
>

<!ELEMENT root (handler-ref+)>
<!ATTLIST root
    level    CDATA #REQUIRED
    resource CDATA #IMPLIED
>

<!ELEMENT handler-ref EMPTY>
<!ATTLIST handler-ref
    ref IDREF #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
    name    CDATA #REQUIRED
    value   CDATA #REQUIRED
>

=== AdachiHjm/zerodrive/zerodrive/src/main/resources/default-logging.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE logging SYSTEM "file:///C:/Users/AdachiHjm/git/zerodrive/zerodrive/src/main/resources/logging_1_0.dtd">

<logging>
    <handler name="STDOUT" class="java.util.logging.ConsoleHandler">
        <property name="output" value="stdout"/>
        <filter class="zerodrive.util.logging.RegexFilter">
            <property name="pattern" value="^[0-9].+$"/>
        </filter>
        <formatter class="java.util.logging.SimpleFormatter">
        </formatter>
    </handler>

    <logger name="zerodrive" additivity="false" level="INFO">
        <handler-ref ref="STDOUT" />
    </logger>

    <root level="INFO">
        <handler-ref ref="STDOUT" />
    </root>
</logging>
